language: python
python:
  - "3.4"

stages:
  - test
  - deploy


jobs:
  include:
    - stage: test
      sudo: required
      services:
        - docker
      name: "Checking Production Container Run"
      script:
        - make check-docker-production

    - stage: test
      sudo: required
      services:
        - docker
      name: "Checking Development Container Run"
      script:
        - make check-docker-dev

    - stage: test
      virtualenv:
        system_site_packages: true
      cache: pip
      install:
        - pip install -r product_microservice/requirements/dev.txt
      name: "Unit Tests"
      script: sh run-tests.sh

    - stage: deploy
      install: npm install -g heroku
      name: "Deploying to Staging"
      only:
        - dev
      script:
        - . ./heroku-helper.sh
        - updateVersion
        - loginHeroku $EMAIL_HEROKU $HEROKU_TOKEN
        - deployMaster $HEROKU_APP product_microservice