language: python
python:
  - "3.4"

stages:
  - check-container
  - test
  - deploy

jobs:
  include:
    - stage: check-container
      sudo: required
      services:
        - docker
      name: "Checking Production Container Run"
      script:
        - make check-docker-production

    - stage: check-container
      sudo: required
      services:
        - docker
      name: "Checking Development Container Run"
      script:
        - make check-docker-dev

    - stage: test
      virtualenv:
        system_site_packages: true
      cache: pip
      install:
        - pip install -r product_microservice/requirements/dev.txt
      name: "Unit Tests"
      script: sh run-tests.sh

    - stage: deploy
      provider: heroku
      api_key:
        heroku/deploy-stg: $HEROKU_DEV_KEY
      app:
        heroku/deploy-stg: $HEROKU_APP

    
