version: '3.6'

services:
  db:
    image: postgres:10.1-alpine
  web:
    build:
      context: .
      dockerfile: production.Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8002:8000
    depends_on:
      - db

volumes:
  postgres_data: