# Generated by Django 2.1.1 on 2018-09-05 19:11

from django.db import migrations, models
from django.contrib.auth.models import User

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_list/photos/')),
                ('description', models.TextField()),
            ],
        ),
    ]
